In [ ]:
# import numpy as np

arr = np.array([ 1 , 2 , 3 , 4 , 5])
print(arr)
print(type(arr)) 

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# import numpy as np

arr1 = np.array([1 , 2 , 3 , 4 , 0])
arr2 = np.array([5 , 6 , 7 , 8 , 9])

arry3 = arr1 + arr2
print(arry3)

arr3 = arr1 - arr2 
print(arr3)



[ 6  8 10 12  9]
[-4 -4 -4 -4 -9]


In [ ]:
# import numpy as np

arr = np.array([ 1 , 2 , 3 , 4 , 5])

print(sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.sqrt(arr))

15
1
5
3.0
[1.         1.41421356 1.73205081 2.         2.23606798]


In [12]:
arr = np.array([ [1 , 2 , 3] , [4 , 5 , 6]])

print(arr) 
print(arr.shape)  # row and column count
print(arr.size) # total number of elements
print(arr.dtype) # data type of elements

import numpy as np

[[1 2 3]
 [4 5 6]]
(2, 3)
6
int64


In [ ]:
arr = np.array([ 
                [[0 , 1] ,[0 , 1] ,[0 , 1]] , 
                [[0 , 1] ,[0 , 1] ,[0 , 1]] , 
                [[8 , 9] ,[0 , 1] ,[0 , 1]]
            ])
print(arr)
print(arr.shape)

[[[0 1]
  [0 1]
  [0 1]]

 [[0 1]
  [0 1]
  [0 1]]

 [[8 9]
  [0 1]
  [0 1]]]
(3, 3, 2)


In [20]:
arr = np.array([10 , 20 , 15 , 18 , 14 , 26 ])
condition = arr > 15
print(condition)


[False  True False  True False  True]


In [23]:
import numpy as np
# Q1.
arr_1 = np.array([ 
                [12 , 5 , 7 , 20] ,
                [3 , 15 , 8 , 2],
                [10 , 25 , 6 , 18],
                [4 , 11 , 30 , 9]
                ])

# extract all elements that are greater than 10 or less than 5 
# And != 15

arr = arr_1[ (arr_1 > 10) | (arr_1 < 5) & (arr_1 != 15) ]
print(arr)

[12 20  3 15  2 25 18  4 11 30]


In [24]:
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
arr = np.full((3,4) , 7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [26]:
arr = np.empty((2,3))
print(arr)

[[4.9e-323 9.9e-323 7.4e-323]
 [8.9e-323 6.9e-323 1.3e-322]]


In [18]:
arr_1 = np.array([ [1 , 2 , 3] , [4 , 5 , 6]])

print(arr_1[1 , 2])

6
