In [1]:
import numpy as np

arr = np.array([ 1 , 2 , 3 , 4 , 5])
print(arr)
print(type(arr)) 

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

arr1 = np.array([1 , 2 , 3 , 4 , 0])
arr2 = np.array([5 , 6 , 7 , 8 , 9])

arry3 = arr1 + arr2
print(arry3)

arr3 = arr1 - arr2 
print(arr3)



[ 6  8 10 12  9]
[-4 -4 -4 -4 -9]


In [9]:
import numpy as np

arr = np.array([ 1 , 2 , 3 , 4 , 5])

print(sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.sqrt(arr))

15
1
5
3.0
[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
arr = np.array([ [1 , 2 , 3] , [4 , 5 , 6]])

print(arr)
print(arr.shape)  # row and column count

[[1 2 3]
 [4 5 6]]
(2, 3)
